owner: adamanteye
repo: upptime

sites:
  - name: Note
    url: https://note.adamanteye.cc
  - name: Pastebin
    url: https://bin.adamanteye.cc
  - name: WakaTime
    url: https://wakatime.adamanteye.cc
  - name: Hedgedoc
    url: https://doc.adamanteye.cc
  - name: Taskchampion Sync Server
    url: https://task.adamanteye.cc

status-website:
  cname: status.adamanteye.cc
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Status Page** of Adamanteye"
  introMessage: "Services hosted by Adamanteye"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/20 * * * *"
